spring:
  kafka:
    bootstrap-servers: 192.168.0.144:9092 # замени на IP контейнера с Kafka в Ubuntu
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 0
      properties:
        max.block.ms: 3000               # <== максимальное время блокировки при send
        metadata.max.age.ms: 1000        # <== как часто обновлять метаданные топика
        request.timeout.ms: 3000         # <== таймаут сетевого запроса
        delivery.timeout.ms: 3000        # <== полный лимит времени доставки
    properties:
      spring.json.add.type.headers: false
    topics:
      transfer-requests: transfer-requests

server:
  port: 8081
  #tomcat:
    #threads:
      #max: 500
    #accept-count: 1000

logging:
  level:
    root: INFO
    com.gpts: DEBUG # только твои пакеты — можно видеть подробные логи
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info
